services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: urlshortener
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/urlshortener
    depends_on:
      - db

volumes:
  pgdata:
